name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: List files in target directory
      - name: List files in target directory
        run: ls -la target

      # Step 5: Upload the JAR artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/*.jar  # Captura qualquer arquivo JAR gerado

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Download the JAR artifact built in the previous job
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-file

      # Step 2: List downloaded artifact to confirm the location
      - name: List downloaded artifact
        run: ls -la

      # Step 3: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Apiexample
          environment_name: Apiexample-env
          region: us-east-1
          deployment_package: $(ls *.jar)  # Usa o nome correto do arquivo JAR encontrado
          version_label: ${{ github.sha }}

      # Step 4: Clean up
      - name: Clean up
        run: rm -f *.jar
